spring:
  application:
    name: ${AS_NAME:authserver}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:pieauth}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

server:
  address: 0.0.0.0
  port: ${AS_SERVER_PORT:9001}

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([$thread]) %yellow(%logger{15}) - %msg%n}


jwt:
  secret-key: b6b825f5c11d980c01d03be7fff5877f90d2b964dcdab6fe632fb4640bc53cbebe528a360a7608319883253388afa11072e9056ec11fa1f9b65dd39b4323a51c
  access-expiration: 3600000  # 1시간 (1시간 = 60 * 60 * 1000ms)
  refresh-expiration: 1296000000  # 15일 (15일 = 15 * 24 * 60 * 60 * 1000ms)
